name: Spell Check

on:
  push:
    paths-ignore:
      - '**.pdf'
      - '**.md'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Spell Check LaTeX files
        uses: streetsidesoftware/cspell-action@v5
        with:
          files: '**/*.tex'
